### ISSUE TITLE
Update dat contents on run

### ISSUE THREAD

**Issue by pfrazee** [joehand/dat-push#1]
The flow I want to have is, to be able to run `dat-push` the first time, make some changes, and then run `dat-push` to publish the updates.

What seems to happen, right now, is that `dat-push` doesn't update the dat with changes that happened since the last push. (Actually, to my surprise, neither did the normal `dat` command: I had to start sharing with `dat`, and then `touch` my modified file.)

Could `dat-push`  update the archive on subsequent runs?

**Comment by joehand** [comment]
Hmm. Ya, that should definitely be what happens. Do you have different versions of hyperdrive or hyperdrive-import-files? 

We fixed this in hyperdrive 7.3.0 and hyperdrive-import-files 2.2.0. The `dat` CLI update needs to be released, but this fix is on master.

I thought this was working locally but haven't looked at it closely. If updating to those versions doesn't work, I'll take a look Monday.

**Comment by pfrazee** [comment]
> Do you have different versions of hyperdrive or hyperdrive-import-files?

I globally installed dat-push from npm, so I should have been at latest for everything.

**Comment by joehand** [comment]
Ah! I realized what's probably happening. Dat-push doesn't update the archive - it just pushes whatever is in it. So to make it work, you'd have to reshare with `dat` then `dat-push`. 

Should a push update and push the archive? Right now it requires an explicit "commit" (dat share) before you push. But we could make a push an implicit commit as well. 

I'm tempted to go this second route because otherwise we get some weird bugs when files differ from metadata, so we'd have to check manually for changes before a push.

**Comment by pfrazee** [comment]
Yeah I'd definitely prefer that a push was an implicit commit, given that there's not any concept of a staging area.

**Comment by joehand** [comment]
Ya, sounds good! Published in `3.1.0`.

May have to work on the UI to show sharing progress later but this will do for now.
